name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/index.js'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/index.js'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/nodejs-argo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
